version: '2.1'
services:
  product:
    build: microservices/anime-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  recommendation:
    build: microservices/anime-recommendation-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  review:
    build: microservices/anime-review-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  product-composite:
    build: microservices/anime-composite-service
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker