server.port: 7000
server:
  error:
    include-message: always

app:
  anime-service:
    host: localhost
    port: 7001
  anime-recommendation-service:
    host: localhost
    port: 7002
  anime-review-service:
    host: localhost
    port: 7003

logging:
  level:
    root: INFO
    com.albayrak: DEBUG

---
spring.profiles: docker
server.port: 8080

app:
  anime-service:
    host: anime
    port: 8080
  anime-recommendation-service:
    host: recommendation
    port: 8080
  anime-review-service:
    host: review
    port: 8080